name: Exploratory Data Analysis Efraud dataset
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Exploratory Data Analysis
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          pip install -r requirements.txt
          python main.py
          echo "### EDA Report ###" > report.md
          cat result.txt >> report.md
          echo "![](check_data.png)" >> report.md
          cml-send-comment report.md